name: ci

on:
  workflow_dispatch:
    inputs:
      cairo_version:
        description: 'Cairo 1.0 release version'     
        required: true 
      scarb_version:
        description: 'Scarb release version'     
        required: true 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: gizatechxyz/cairo-1.0:${{ github.event.inputs.cairo_version }}
          build-args: |
            CAIRO_GIT_TAG=${{ github.event.inputs.cairo_version }}
            SCARB_VERSION=${{ github.event.inputs.scarb_version }}